steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/bldc-integration-with-gcp/github.com/nareshbogadevops/thebookie:$SHORT_SHA', '.']
